services:
  web:
    build: . # Dockerfile from current dir
    container_name: fastapi-dashboard
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - ./app:/src/app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
