services:
  web:
    build: . # use Dockerfile in current dir
    container_name: protocol-parser
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - ./app:/src/app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
