[project]
name = "fastapi-dashboard"
version = "1.0.0"
description = "A FastAPI based dashboard WebApp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "itsdangerous>=2.2.0",
    "openai>=2.11.0",
    "passlib[argon2]>=1.7.4",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.45",
    "uvicorn[standard]>=0.38.0",
]
